repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-ast
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.18.0
          - "@rushstack/eslint-patch@1.1.3"
          - "@typescript-eslint/parser@5.29.0"
          - eslint-import-resolver-node@0.3.6
          - eslint-import-resolver-typescript@2.7.1
          - eslint-plugin-import@2.26.0
          - eslint-plugin-jsx-a11y@6.5.1
          - eslint-plugin-react-hooks@4.6.0
          - "@next/eslint-plugin-next@12.1.6"
          - eslint-config-next@12.1.6
          - eslint-loader@1.6.1
          - eslint-plugin-react@6.10.3
          - babel-eslint@6.1.2
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
